import type { Metadata } from "next";
import { Suspense } from "react";
import './global.css'
import CLoading from "@/components/loadings/component/cLoading";

export const metadata: Metadata = {
  title: "AnimeList",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <Suspense fallback={<CLoading />}>
          {children}
        </Suspense>
      </body>
    </html>
  );
}
