import type { Metadata } from "next";
import './global.css'
import { Suspense } from "react";
import Loading from "./components/loading/loading";
import Render from "./components/render/render";


export const metadata: Metadata = {
  title: "AnimeList",
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>

        <Render />
        
        <Suspense fallback={<Loading />}>
          {children}
        </Suspense>
   
      </body>
    </html>
  );
}
