import type { Metadata } from "next";
import { Header } from "./components/header/header";
import './global.css'
import { Suspense } from "react";
import Loading from "./components/loading/loading";


export const metadata: Metadata = {
  title: "AnimeList",
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <Header />
        
        <Suspense fallback={<Loading />}>
          {children}
        </Suspense>
   
      </body>
    </html>
  );
}
